### PR TITLE
Fix storage snapshot sync

### LINKED ISSUE #897: Malformed `getapplicationlog` RPC request result
**Describe the bug**
While testing the https://github.com/nspcc-dev/neo-go/pull/3402, I discovered that `ApplicationLogs` plugin returns improper result of `getapplicationlog` RPC call. The result contains wrong `contract` field value of `notifications` section. For example, `getapplicationlog` for genesis block of mainnet has exactly the same notification's contract hash for all notificaitons (for both OnPersist and PostPersist triggers), `0xd2a4cff31913016155e38e474a2c06d08be276cf` (native GasToken). While I'd expect contract hashes of notifications to have proper values.

This bug was introduced in master after 20th of March, because in that day I successfully built neo-modules master and checked genesis block notifications within the scope of https://github.com/neo-project/neo/issues/2834#issuecomment-2008142934.  I'm suspecting that this bug was introduced by https://github.com/neo-project/neo-modules/pull/865, because this PR was merged 21th of March and makes a lot of changes in ApplicationLogs plugin, but we need to check.

**To Reproduce**
1. Build fresh neo-modules master and fresh NeoCLI;
2. Run NeoCLI with RPCServer and ApplicationLogs plugin enabled and start mainnet sync from genesis;
3. Send `getapplicationlog` RPC request to RPC server with genesis block hash;
4. Check the result.

The result from the fresh master is:
```
anna@kiwi:~/Documents/GitProjects/neo-project/neo/src/Neo.CLI/bin/Release/net8.0/linux-x64$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getapplicationlog", "params": ["0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15"] }' localhost:10332 | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2725    0  2583  100   142  49590   2726 --:--:-- --:--:-- --:--:-- 52403
{
   "id" : 1,
   "jsonrpc" : "2.0",
   "result" : {
      "blockhash" : "0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15",
      "executions" : [
         {
            "gasconsumed" : "0",
            "notifications" : [
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "/aP6Q0bqUyolj8SX3a3bZDfJ/f8="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "wO85zuDk6SXGwqBqeeFEDdhvzqw="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "G/V1qxGJaIQTYQo1oSiGzeC2bHI="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "vvIEMUA2KnfBUJnH5kwS9wC2Zdo="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "axI92L7HGGSIUrvHhZXjU2oFj58="
                        },
                        {
                           "type" : "Integer",
                           "value" : "100000000"
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "9WPqQLwoPU0OBcSOowWz8qBzQO8="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "axI92L7HGGSIUrvHhZXjU2oFj58="
                        },
                        {
                           "type" : "Integer",
                           "value" : "5200000000000000"
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "z3bii9AGLEpHjuNVYQETGfPPpNI="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "e8aBwKH3HVQ0V7aLuo1fn91OXsw="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "4pXjkVRMF4rZTwPsTc3/eFNOz0k="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "WIcXEX4KqBByr6tx0t2J/nxLkv4="
                        }
                     ]
                  }
               }
            ],
            "stack" : [],
            "trigger" : "OnPersist",
            "vmstate" : "HALT"
         },
         {
            "gasconsumed" : "0",
            "notifications" : [
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "lpSe1ILnxgqu7GkVUPGz1ZkUYZQ="
                        },
                        {
                           "type" : "Integer",
                           "value" : "50000000"
                        }
                     ]
                  }
               }
            ],
            "stack" : [],
            "trigger" : "PostPersist",
            "vmstate" : "HALT"
         }
      ]
   }
}
```

**Expected behavior**
The expected result is mentioned in https://github.com/neo-project/neo/issues/2834#issuecomment-2008142934, it should have proper contract hashes for all genesis notifications:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getapplicationlog", "params": ["0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15"] }' localhost:10332 | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2725    0  2583  100   142   644k  36298 --:--:-- --:--:-- --:--:--  887k
{
   "id" : 1,
   "jsonrpc" : "2.0",
   "result" : {
      "blockhash" : "0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15",
      "executions" : [
         {
            "gasconsumed" : "0",
            "notifications" : [
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "/aP6Q0bqUyolj8SX3a3bZDfJ/f8="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "wO85zuDk6SXGwqBqeeFEDdhvzqw="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "G/V1qxGJaIQTYQo1oSiGzeC2bHI="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "vvIEMUA2KnfBUJnH5kwS9wC2Zdo="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "axI92L7HGGSIUrvHhZXjU2oFj58="
                        },
                        {
                           "type" : "Integer",
                           "value" : "100000000"
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "9WPqQLwoPU0OBcSOowWz8qBzQO8="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "axI92L7HGGSIUrvHhZXjU2oFj58="
                        },
                        {
                           "type" : "Integer",
                           "value" : "5200000000000000"
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "z3bii9AGLEpHjuNVYQETGfPPpNI="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "e8aBwKH3HVQ0V7aLuo1fn91OXsw="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "4pXjkVRMF4rZTwPsTc3/eFNOz0k="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "WIcXEX4KqBByr6tx0t2J/nxLkv4="
                        }
                     ]
                  }
               }
            ],
            "stack" : [],
            "trigger" : "OnPersist",
            "vmstate" : "HALT"
         },
         {
            "gasconsumed" : "0",
            "notifications" : [
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "lpSe1ILnxgqu7GkVUPGz1ZkUYZQ="
                        },
                        {
                           "type" : "Integer",
                           "value" : "50000000"
                        }
                     ]
                  }
               }
            ],
            "stack" : [],
            "trigger" : "PostPersist",
            "vmstate" : "HALT"
         }
      ]
   }
}
```

**Platform:**
 - Version:
   - core: 3a12f3dd4d1400e842d58a12f0057607627e511e
   - modules: 66573ed24bb6d1f5c83602d926cb7355b823ea49

**(Optional) Additional context**

This bug is critical for 3.7, should be solved before the release.

### PR DESCRIPTION
**Pull request by cschuchardt88**
_Change Log_
---
- Fixed sync order

_**Note**_:  DO NOT need to resync

Closes #897

### CODE REVIEW

**Review by superboyiii — APPROVED** [review]
Good job. Correct now.

**Review by Jim8y — APPROVED** [review]

File: src/ApplicationLogs/LogReader.cs [hunk 1]
```diff
@@ -385,26 +384,27 @@ private JObject TransactionToJObject(UInt256 txHash)
...
                 triggerList.Add(BlockItemToJObject(blockOnPersist));
+
+            var blockPostPersist = _neostore.GetBlockLog(blockHash, TriggerType.PostPersist);
             if (blockPostPersist != null)
                 triggerList.Add(BlockItemToJObject(blockPostPersist));
 
             blockJson["executions"] = triggerList.ToArray();
+
+            if (blockOnPersist == null && blockPostPersist == null)
+                return null;
```
Comment (shargon) [inline src/ApplicationLogs/LogReader.cs:402]: Why create the `JObject` to return null later? I think it's more efficient the previous version

**Review by AnnaShaleva — COMMENTED** [review]
The fix itself looks legit, let me test it.

**Review by vncoelho — APPROVED** [review]
Good job,@cschuchardt88

**Review by AnnaShaleva — CHANGES_REQUESTED** [review]
Fixed for the events with different triggers, but still not fixed for events with the same trigger. The updated code gives wrong hash for the Neo and Gas initial supply `Transfer` events (they have Management's hash in the `contract` field):
image
Here's the full updated `getapplicationlog` result for the genesis block:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getapplicationlog", "params": ["0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15"] }' localhost:10332 | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2725    0  2583  100   142   613k  34558 --:--:-- --:--:-- --:--:--  887k
{
   "id" : 1,
   "jsonrpc" : "2.0",
   "result" : {
      "blockhash" : "0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15",
      "executions" : [
         {
            "gasconsumed" : "0",
            "notifications" : [
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "/aP6Q0bqUyolj8SX3a3bZDfJ/f8="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "wO85zuDk6SXGwqBqeeFEDdhvzqw="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "G/V1qxGJaIQTYQo1oSiGzeC2bHI="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "vvIEMUA2KnfBUJnH5kwS9wC2Zdo="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "axI92L7HGGSIUrvHhZXjU2oFj58="
                        },
                        {
                           "type" : "Integer",
                           "value" : "100000000"
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "9WPqQLwoPU0OBcSOowWz8qBzQO8="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "axI92L7HGGSIUrvHhZXjU2oFj58="
                        },
                        {
                           "type" : "Integer",
                           "value" : "5200000000000000"
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "z3bii9AGLEpHjuNVYQETGfPPpNI="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "e8aBwKH3HVQ0V7aLuo1fn91OXsw="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "4pXjkVRMF4rZTwPsTc3/eFNOz0k="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Deploy",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "WIcXEX4KqBByr6tx0t2J/nxLkv4="
                        }
                     ]
                  }
               }
            ],
            "stack" : [],
            "trigger" : "OnPersist",
            "vmstate" : "HALT"
         },
         {
            "gasconsumed" : "0",
            "notifications" : [
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "lpSe1ILnxgqu7GkVUPGz1ZkUYZQ="
                        },
                        {
                           "type" : "Integer",
                           "value" : "50000000"
                        }
                     ]
                  }
               }
            ],
            "stack" : [],
            "trigger" : "PostPersist",
            "vmstate" : "HALT"
         }
      ]
   }
}
```

**Comment by AnnaShaleva** [comment]
> Good job. Correct now.

@superboyiii, am I doing something wrong? Are you sure you've got the correct result?

File: src/ApplicationLogs/Store/NeoStore.cs [hunk 2]
```diff
@@ -109,7 +103,7 @@ public void PutTransactionEngineLogState(UInt256 hash, IReadOnlyList<LogEventArg
             var ids = new List<Guid>();
             foreach (var log in logs)
                 ids.Add(lss.PutEngineState(EngineLogState.Create(log.ScriptHash, log.Message)));
-            lss.PutTransactionEngineState(hash, TransactionEngineLogState.Create(ids.ToArray()));
+            lss.PutTransactionEngineState(hash, TransactionEngineLogState.Create([.. ids]));
```
[the remark this answers is not in the document]
Comment (cschuchardt88) [reply src/ApplicationLogs/Store/NeoStore.cs:106]: `dotnet` `8.0` new way of doing it

File: src/ApplicationLogs/LogReader.cs [hunk 3]
```diff
@@ -207,7 +206,7 @@ private void OnCommitting(NeoSystem system, Block block, DataCache snapshot, IRe
                 foreach (var appEng in applicationExecutedList.Where(w => w.Transaction != null))
                 {
                     var logs = _logEvents.Where(w => w.ScriptContainer.Hash == appEng.Transaction.Hash).ToList();
-                    if (logs.Any())
+                    if (logs.Count != 0)
```
[the remark this answers is not in the document]
Comment (cschuchardt88) [reply src/ApplicationLogs/LogReader.cs:209]: Faster this way in `dotnet` `8.0`

File: src/ApplicationLogs/LogReader.cs (hunk 1 above)
Comment (cschuchardt88) [reply src/ApplicationLogs/LogReader.cs:402]: Reason is caused by a caching issue in `LevelDb` since we are not using the right `API` calls to the `libleveldb.dll`. The old way will overwrite the previous; in this case its `_neostore.GetBlockLog(blockHash, TriggerType.OnPersist);` results that will be overwritten with the next `API` call `_neostore.GetBlockLog(blockHash, TriggerType.PostPersist);`

**Comment by superboyiii** [comment]
> > Good job. Correct now.
> 
> @superboyiii, am I doing something wrong? Are you sure you've got the correct result?

My fault, wrong data was compared in test. Yes, the `transfer` event in `OnPersist` trigger should be for `GAS` and `NEO`, but not for `0xfffdc93764dbaddd97c48f252a53ea4643faa3fd(contract management)` itself. @cschuchardt88 
b07128561a78e300118a27a4fb9fcf1

**Comment by cschuchardt88** [comment]
@AnnaShaleva @superboyiii 

All check out but the `block` with hash of `0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15`  and index of `0`.

The reason for this is because `NeoSystem` gets initialized before any `Plugins` get loaded.

For example block with hash of `0x8e1db6017a1205501a8689ff1657ff81d264bca2e4afba12f673a8e4bad6bad2` checks out valid.
---
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockhash": "0x8e1db6017a1205501a8689ff1657ff81d264bca2e4afba12f673a8e4bad6bad2",
        "executions": [
            {
                "trigger": "OnPersist",
                "vmstate": "HALT",
                "gasconsumed": "0",
                "stack": [],
                "notifications": [
                    {
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "axI92L7HGGSIUrvHhZXjU2oFj58="
                                },
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "Integer",
                                    "value": "17589000"
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "UDiCgEgZdLrr634iF9YNyKdJeLo="
                                },
                                {
                                    "type": "Integer",
                                    "value": "7611220"
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "trigger": "PostPersist",
                "vmstate": "HALT",
                "gasconsumed": "0",
                "stack": [],
                "notifications": [
                    {
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "lpSe1ILnxgqu7GkVUPGz1ZkUYZQ="
                                },
                                {
                                    "type": "Integer",
                                    "value": "50000000"
                                }
                            ]
                        }
                    }
                ]
            }
        ]
    }
}
```

**Comment by AnnaShaleva** [comment]
> All check out but the block with hash of 0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15 and index of 0.
The reason for this is because NeoSystem gets initialized before any Plugins get loaded.

@cschuchardt88, we need ApplicationLogs plugin to work correctly even for genesis block, it's important.

**Comment by cschuchardt88** [comment]
@AnnaShaleva 

This seems to be a problem with `NeoSystem`; the way plugins are loaded. I don't think genesis block requests block information from the network. What i see is happening; is that genesis block is initialized already before plugins get loaded and started. Maybe @Jim8y @shargon can you confirm?

**Comment by cschuchardt88** [comment]
@shargon any reason why `0xfffdc93764dbaddd97c48f252a53ea4643faa3fd` `ContractManagement` contract work be the hash for  `OnPersist` trigger?

**Comment by shargon** [comment]
> @shargon any reason why `0xfffdc93764dbaddd97c48f252a53ea4643faa3fd` `ContractManagement` contract would be the hash for `OnPersist` trigger?

I don't understand you, could you explain it? the hash for `OnPersist`?

**Comment by cschuchardt88** [comment]
@shargon When I receive `applicationExecutedList` from on `Blockchain.Committing` event I get the `NotifyEventArgs` and when accessing `NotifyEventArgs.ScriptHash` I am getting `0xfffdc93764dbaddd97c48f252a53ea4643faa3fd` not `0xd2a4cff31913016155e38e474a2c06d08be276cf`. Any thoughts?

Correct response
---
```json
{
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "axI92L7HGGSIUrvHhZXjU2oFj58="
                                },
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "Integer",
                                    "value": "17589000"
                                }
                            ]
                        }
                    }
```

**Comment by cschuchardt88** [comment]
@AnnaShaleva @superboyiii @shargon @Jim8y 

I look at https://github.com/neo-project/neo/commit/b467613884ef4196283f9f303897dedb0c3de36d `Native` contract now emit `deploy/update` events. What you are seeing is correct.

This is ready for merge.

**Review by AnnaShaleva — COMMENTED** [review]
> This is ready for merge.

I don't think so. https://github.com/neo-project/neo-modules/pull/898#pullrequestreview-1998190419 and https://github.com/neo-project/neo-modules/pull/898#issuecomment-2068404802 is still not fixed.

**Comment by cschuchardt88** [comment]
@shargon what test have you done to make sure `notifications` are right?

@AnnaShaleva 
Please see _below_; maybe `GetContractState` is broken or still isn't fixed. 

https://github.com/neo-project/neo/blob/ef43618e42698f66a711b5ceacb8dd5fbef6f99c/src/Neo/SmartContract/Native/ContractManagement.cs#L69-L100

**Comment by cschuchardt88** [comment]
@AnnaShaleva @superboyiii Test again should be fixed now. There was a memory leak because the project isn't marked as `nullable` so when using a `null` `?` and not making it `!` after you get an object will have it keep overwriting the variable when using `out` or `ref`.

**Review by AnnaShaleva — CHANGES_REQUESTED** [review]
> Now I get:

Your result is still not correct. All Deploy notifications have invalid contract hash, and also one Transfer notification has invalid contract hash. The expected result is attached in the "Expected behaviour" section of https://github.com/neo-project/neo-modules/issues/897.

**Comment by superboyiii** [comment]
@cschuchardt88 You could always check original one by v3.6.2 RPC:
curl -X POST http://seed1.neo.org:10332 -d '{"jsonrpc":"2.0","method":"getapplicationlog","params":["0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15"],"id":1}'
You current result mistakenly get wrong contract hash for NEO. As we all know 100000000 NEO  and 52000000 GAS has been transferred into consensus multisig address in genesis block. That's where these 2 `transfer` event from.

**Comment by cschuchardt88** [comment]
@AnnaShaleva @superboyiii 

My bad forgot to commit.

http://seed1.neo.org:10332
---
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockhash": "0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15",
        "executions": [
            {
                "trigger": "OnPersist",
                "vmstate": "HALT",
                "gasconsumed": "0",
                "stack": [],
                "notifications": [
                    {
                        "contract": "0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "axI92L7HGGSIUrvHhZXjU2oFj58="
                                },
                                {
                                    "type": "Integer",
                                    "value": "100000000"
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "axI92L7HGGSIUrvHhZXjU2oFj58="
                                },
                                {
                                    "type": "Integer",
                                    "value": "5200000000000000"
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "trigger": "PostPersist",
                "vmstate": "HALT",
                "gasconsumed": "0",
                "stack": [],
                "notifications": [
                    {
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "lpSe1ILnxgqu7GkVUPGz1ZkUYZQ="
                                },
                                {
                                    "type": "Integer",
                                    "value": "50000000"
                                }
                            ]
                        }
                    }
                ]
            }
        ]
    }
}
```
http://127.0.0.1:10332
---
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockhash": "0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15",
        "executions": [
            {
                "trigger": "OnPersist",
                "vmstate": "HALT",
                "gasconsumed": "0",
                "stack": [],
                "notifications": [
                    {
                        "contract": "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                        "eventname": "Deploy",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "/aP6Q0bqUyolj8SX3a3bZDfJ/f8="
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                        "eventname": "Deploy",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "wO85zuDk6SXGwqBqeeFEDdhvzqw="
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                        "eventname": "Deploy",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "G/V1qxGJaIQTYQo1oSiGzeC2bHI="
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                        "eventname": "Deploy",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "vvIEMUA2KnfBUJnH5kwS9wC2Zdo="
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "axI92L7HGGSIUrvHhZXjU2oFj58="
                                },
                                {
                                    "type": "Integer",
                                    "value": "100000000"
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                        "eventname": "Deploy",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "9WPqQLwoPU0OBcSOowWz8qBzQO8="
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "axI92L7HGGSIUrvHhZXjU2oFj58="
                                },
                                {
                                    "type": "Integer",
                                    "value": "5200000000000000"
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                        "eventname": "Deploy",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "z3bii9AGLEpHjuNVYQETGfPPpNI="
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                        "eventname": "Deploy",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "e8aBwKH3HVQ0V7aLuo1fn91OXsw="
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                        "eventname": "Deploy",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "4pXjkVRMF4rZTwPsTc3/eFNOz0k="
                                }
                            ]
                        }
                    },
                    {
                        "contract": "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                        "eventname": "Deploy",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "ByteString",
                                    "value": "WIcXEX4KqBByr6tx0t2J/nxLkv4="
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "trigger": "PostPersist",
                "vmstate": "HALT",
                "gasconsumed": "0",
                "stack": [],
                "notifications": [
                    {
                        "contract": "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                        "eventname": "Transfer",
                        "state": {
                            "type": "Array",
                            "value": [
                                {
                                    "type": "Any"
                                },
                                {
                                    "type": "ByteString",
                                    "value": "lpSe1ILnxgqu7GkVUPGz1ZkUYZQ="
                                },
                                {
                                    "type": "Integer",
                                    "value": "50000000"
                                }
                            ]
                        }
                    }
                ]
            }
        ]
    }
}
```

File: src/ApplicationLogs/Store/Models/BlockchainEventModel.cs [hunk 4]
```diff
@@ -12,15 +12,14 @@
...
 using Neo;
 using Neo.VM.Types;
-using Array = System.Array;
 
 namespace ApplicationLogs.Store.Models
 {
     public class BlockchainEventModel
     {
-        public UInt160 ScriptHash { get; private init; } = UInt160.Zero;
+        public UInt160 ScriptHash { get; private init; } = new();
```
Comment (shargon) [inline src/ApplicationLogs/Store/Models/BlockchainEventModel.cs:20]: Why create a new empty instance if we have one in memory?

Comment (cschuchardt88) [reply src/ApplicationLogs/Store/Models/BlockchainEventModel.cs:20]: Its a memory leak. That's the reason why we had this problem with different addresses in the state. It uses the `class` instance of `UInt160.Zero` when doing `ScriptHash.Deserialize()`. It will keep writing to the same buffer. So i need a new instance either way.

Comment (shargon) [reply src/ApplicationLogs/Store/Models/BlockchainEventModel.cs:20]: If we reuse the same instance, how can be a memory leak?

Comment (cschuchardt88) [reply src/ApplicationLogs/Store/Models/BlockchainEventModel.cs:20]: @shargon we are using the same instance. That was the problem. The instance being `UInt160.Zero`

**Comment by cschuchardt88** [comment]
@AnnaShaleva @superboyiii any update on testing the state?

**Review by AnnaShaleva — APPROVED** [review]
Checked the updated version, seems to work correctly now.

**Review by superboyiii — APPROVED** [review]
Looks good from my local results.
