### PR TITLE
Don't log index check error

### LINKED ISSUE #724: Restart consensus node will cause InvalidOperationException
**Describe the bug**
Restart consensus node will cause InvalidOperationException

**To Reproduce**
1. Create a private chain, whatever single consensus or 4 consensus
2. Start consensus and stop
3. Restart

**Expected behavior**
`System.InvalidOperationException: Operation is not valid due to the current state of the object.`
Persist could still go on.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ZhangTao1596**
Close #724

### CODE REVIEW

**Comment by superboyiii** [comment]
Test OK.

**Review by superboyiii — DISMISSED** [review]

**Review by shargon — APPROVED** [review]

**Review by vncoelho — CHANGES_REQUESTED** [review]
1 week for me to check.
But looks good.

File: src/DBFTPlugin/Consensus/ConsensusService.cs [hunk 1]
```diff
@@ -72,6 +72,8 @@ private void OnPersistCompleted(Block block)
         {
             Log($"Persisted {nameof(Block)}: height={block.Index} hash={block.Hash} tx={block.Transactions.Length} nonce={block.Nonce}");
             knownHashes.Clear();
+            if (context.Block.Index == block.Index && context.CommitSent)
```
Comment (vncoelho) [inline src/DBFTPlugin/Consensus/ConsensusService.cs:75]: Why does it need to be Committed?
Maybe it directly received the block.

Comment (ZhangTao1596) [reply src/DBFTPlugin/Consensus/ConsensusService.cs:75]: Only committed node saves context.

**Review by vncoelho — APPROVED** [review]

File: src/DBFTPlugin/Consensus/ConsensusContext.cs [hunk 2]
```diff
@@ -264,6 +264,11 @@ public void Save()
             store.PutSync(ConsensusStateKey, this.ToArray());
         }
 
+        public void Delete()
+        {
+            store.Delete(ConsensusStateKey);
```
Comment (erikzhang) [inline src/DBFTPlugin/Consensus/ConsensusContext.cs:269]: We don't need to delete it. Because it will be replaced in the next block.

Comment (ZhangTao1596) [reply src/DBFTPlugin/Consensus/ConsensusContext.cs]: Updated. How do you think?

Comment (superboyiii) [reply src/DBFTPlugin/Consensus/ConsensusContext.cs]: > We don't need to delete it. Because it will be replaced in the next block.

But will show error in log.

Comment (ZhangTao1596) [reply src/DBFTPlugin/Consensus/ConsensusContext.cs]: This log is necessary. You use a wrong Neo.dll.

**Review by erikzhang — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Comment by vncoelho** [comment]
Perfect,maybe update PR title.
